---
fail_fast: true

repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-tidy
        args: ["--config-file=.clang-tidy", "--checks=*"]
      - id: uncrustify
      - id: cppcheck
      - id: cpplint
      - id: clang-format
